"""
Advanced missing values imputation with:
- LLM-guided context-aware conditional rules
- Statistical fallbacks: mean, median, mode
- KNN-based imputation for numeric columns
- Forward/Backward fill for time-series ordered data
- Constant fill with domain defaults
- fill_none: normalizes business-sensitive columns to None (NaN)
  instead of statistically fabricating values like salary, payment_method, etc.

Business Rule (Non-Predictive Business datasets):
  Columns like salary, payment_method, email, phone, bank_account, dob, gender
  MUST use fill_none — sentinel strings ("unknown", "-", "N/A") are converted
  to actual None/NaN. We never fabricate business identity or financial data.

Full audit tracking of every fill decision.
"""
import re
import pandas as pd
import numpy as np
from typing import List, Optional
from agents.planner_agent import ImputationRule

try:
    from sklearn.impute import KNNImputer
    SKLEARN_AVAILABLE = True
except ImportError:
    SKLEARN_AVAILABLE = False


# Sentinel strings that are treated the same as NaN
_NULL_STRINGS = {"", "nan", "none", "<na>", "unknown", "-", "n/a", "null", "?", "na",
                 "not provided", "no data", "undefined", "missing", "n.a.", "n.a"}


# ─────────────────────────────────────────────────────────────
# Business-Sensitive Column Pattern Guard
# These column types must NEVER be statistically imputed in
# Non-Predictive Business datasets. They use fill_none instead.
# ─────────────────────────────────────────────────────────────
_BUSINESS_SENSITIVE_PATTERNS = [
    # Financial / compensation
    "salary", "wage", "wages", "income", "pay", "compensation",
    "bonus", "ctc", "package", "remuneration", "stipend",
    # Payment methods
    "payment_method", "payment_mode", "pay_method", "pay_mode",
    "mode_of_payment", "payment_type", "pay_type",
    # Banking / financial account
    "bank_account", "bank_no", "account_no", "account_number",
    "routing", "routing_no", "ifsc", "swift", "iban",
    "credit_card", "card_number", "card_no", "cvv",
    # Contact (already protected in dedup — also guard here)
    "email", "mail", "phone", "mobile", "contact_no",
    # Government IDs
    "ssn", "social_security", "national_id", "aadhaar", "aadhar",
    "pan", "pan_no", "passport", "voter_id",
    # Personal sensitive demographics
    "dob", "date_of_birth", "birth_date", "birthdate",
    "gender", "sex",
    "marital_status", "marital", "religion", "caste", "ethnicity", "race",
]


def _is_business_sensitive_column(col_name: str) -> bool:
    """
    Returns True if the column name matches any business-sensitive pattern.
    These columns must use fill_none in Non-Predictive Business mode —
    never fill with mean/median/mode/KNN/forward-fill/backward-fill.
    """
    col_lower = col_name.lower().replace(" ", "_")
    return any(pat in col_lower for pat in _BUSINESS_SENSITIVE_PATTERNS)


def _is_effectively_null(val) -> bool:
    if pd.isna(val):
        return True
    return str(val).strip().lower() in _NULL_STRINGS


class SmartImputer:
    """
    Multi-phase imputation engine:

    Phase 1 — LLM Contextual Rules:
        AI-generated conditional rules like "IF customer_type == 'B2B' THEN priority = 'High'"

    Phase 2 — Statistical Fallback (per-column strategy):
        fill_none      — business-sensitive cols: sentinel strings → None/NaN (NO fabrication)
        fill_median    — skewed numeric
        fill_mean      — normally distributed numeric
        fill_mode      — categorical / low-cardinality
        fill_knn       — numeric with correlated neighbors
        fill_constant  — fill with a provided constant
        fill_forward   — time-series propagation forward
        fill_backward  — time-series propagation backward
        fill_interpolate — time-series linear interpolation
        leave_empty    — explicit skip (no change at all)

    CRITICAL RULE:
        For Non-Predictive Business datasets, any column matching
        _BUSINESS_SENSITIVE_PATTERNS is automatically redirected to fill_none —
        even if the caller requests a statistical strategy.

    All decisions are tracked in:
        self.applied_rules      — LLM rule results
        self.statistical_log    — statistical fill results
    """

    def __init__(self):
        self.applied_rules   = []   # LLM rule fills
        self.statistical_log = []   # statistical fallback fills

    # ─────────────────────────────────────────────────────────────
    # Phase 1: LLM Contextual Rules
    # ─────────────────────────────────────────────────────────────
    def apply_smart_rules(
        self, df: pd.DataFrame, rules: List[ImputationRule]
    ) -> pd.DataFrame:
        """Apply context-aware imputation rules generated by the LLM planner."""
        if not rules:
            return df

        print("  [SmartImputer] Applying LLM contextual rules...")
        sorted_rules = sorted(rules, key=lambda r: r.confidence, reverse=True)

        for rule in sorted_rules:
            col = rule.target_column
            if col not in df.columns:
                continue

            # Guard: never apply LLM rule to business-sensitive columns
            if _is_business_sensitive_column(col):
                print(
                    f"  [SmartImputer] Skipped LLM rule for business-sensitive column '{col}' "
                    f"— using fill_none instead"
                )
                df = self.apply_statistical(df, col, "fill_none")
                continue

            missing_mask = df[col].apply(_is_effectively_null)
            if missing_mask.sum() == 0:
                continue

            if rule.condition.lower() == "always":
                condition_mask = pd.Series(True, index=df.index)
            else:
                condition_mask = self._parse_condition(df, rule.condition)

            fill_mask    = missing_mask & condition_mask
            filled_count = int(fill_mask.sum())

            if filled_count > 0:
                df.loc[fill_mask, col] = rule.fill_value
                self.applied_rules.append({
                    "column":      col,
                    "condition":   rule.condition,
                    "fill_value":  rule.fill_value,
                    "rows_filled": filled_count,
                    "confidence":  rule.confidence,
                    "phase":       "LLM Rule",
                })
                print(
                    f"    -> Filled {filled_count} in '{col}' "
                    f"with '{rule.fill_value}' [{rule.condition}]"
                )

        return df

    # ─────────────────────────────────────────────────────────────
    # Phase 2: Statistical Fallback Imputation
    # ─────────────────────────────────────────────────────────────
    def apply_statistical(
        self, df: pd.DataFrame, column: str, strategy: str,
        constant_value: Optional[str] = None,
        dataset_intent: str = "Non-Predictive Business",
    ) -> pd.DataFrame:
        """
        Apply statistical imputation and record detailed audit stats.

        Supported strategies:
            fill_none     — BUSINESS SENSITIVE: convert all sentinel strings → None/NaN
                            (No fabrication — just standardizes messy nulls to real NaN)
            fill_median   — robust for skewed numeric data
            fill_mean     — best for normally distributed numeric data
            fill_mode     — best for categorical / low-cardinality columns
            fill_knn      — KNN imputation for numeric
            fill_forward  — propagate last valid value forward
            fill_backward — propagate next valid value backward
            fill_interpolate — linear interpolation for time-series
            fill_constant — fill with a specific provided constant
            leave_empty   — do nothing (explicit skip)

        BUSINESS RULE:
            If dataset_intent == "Non-Predictive Business" and the column matches
            _BUSINESS_SENSITIVE_PATTERNS, statistical strategies are automatically
            overridden to fill_none — preserving data integrity.
        """
        if strategy == "leave_empty" or column not in df.columns:
            return df

        # ── Business-sensitive guard ──────────────────────────────
        _STATISTICAL = {"fill_mean", "fill_median", "fill_mode", "fill_knn",
                        "fill_forward", "fill_backward", "fill_interpolate"}
        if (
            dataset_intent == "Non-Predictive Business"
            and strategy in _STATISTICAL
            and _is_business_sensitive_column(column)
        ):
            print(
                f"  [GUARD] '{column}' is a business-sensitive column — "
                f"overriding '{strategy}' → fill_none (no statistical fabrication allowed)"
            )
            strategy = "fill_none"

        series = df[column]

        # Unified missing mask: NaN + sentinel strings
        is_missing = series.apply(_is_effectively_null)
        # Standardize sentinel strings to actual NaN first
        df.loc[is_missing, column] = np.nan
        series = df[column]

        missing_count = int(series.isna().sum())
        if missing_count == 0:
            return df

        total_rows = len(series)
        non_null   = series.dropna()
        fill_value_str = None
        extra_stats    = {}

        # ── fill_none ─────────────────────────────────────────────
        # Business-sensitive columns: sentinel strings already converted to NaN above.
        # No further action needed — we intentionally leave them as None/NaN.
        if strategy == "fill_none":
            fill_value_str = "None (NaN)"
            extra_stats    = {
                "method":  "fill_none",
                "note":    "Business-sensitive column: sentinel strings converted to None/NaN. No statistical fabrication.",
            }
            # NaN is already set from sentinel normalization above — nothing more to do.
            print(
                f"  [fill_none] '{column}': {missing_count} missing/sentinel values "
                f"standardized to None/NaN (business-sensitive column — no imputation)"
            )

        # ── fill_median ──────────────────────────────────────────
        elif strategy == "fill_median" and pd.api.types.is_numeric_dtype(series):
            median_val     = float(non_null.median())
            fill_value_str = f"{median_val:.4g}"
            df[column]     = series.fillna(median_val)
            extra_stats    = self._numeric_stats(non_null)
            print(f"  [Impute-Median] '{column}': filled {missing_count} -> {median_val:.4g}")

        # ── fill_mean ────────────────────────────────────────────
        elif strategy == "fill_mean" and pd.api.types.is_numeric_dtype(series):
            mean_val       = float(non_null.mean())
            fill_value_str = f"{mean_val:.4g}"
            df[column]     = series.fillna(mean_val)
            extra_stats    = self._numeric_stats(non_null)
            print(f"  [Impute-Mean]   '{column}': filled {missing_count} -> {mean_val:.4g}")

        # ── fill_mode ────────────────────────────────────────────
        elif strategy == "fill_mode":
            mode_series = non_null.mode()
            if not mode_series.empty:
                mode_val       = mode_series.iloc[0]
                fill_value_str = str(mode_val)
                df[column]     = series.fillna(mode_val)
                extra_stats    = self._categorical_stats(non_null)
                print(f"  [Impute-Mode]   '{column}': filled {missing_count} -> '{mode_val}'")

        # ── fill_knn ─────────────────────────────────────────────
        elif strategy == "fill_knn" and pd.api.types.is_numeric_dtype(series):
            df, knn_filled = self._knn_impute(df, column, missing_count)
            if knn_filled:
                fill_value_str = "KNN"
                extra_stats    = {"method": "KNN (k=5)", "imputed_cells": missing_count}
                print(f"  [Impute-KNN]    '{column}': filled {missing_count} using KNN")

        # ── fill_forward ─────────────────────────────────────────
        elif strategy == "fill_forward":
            df[column]     = series.ffill()
            fill_value_str = "forward-fill"
            extra_stats    = {"method": "Forward Fill (last valid value)"}
            print(f"  [Impute-Ffill]  '{column}': filled {missing_count} forward")

        # ── fill_backward ────────────────────────────────────────
        elif strategy == "fill_backward":
            df[column]     = series.bfill()
            fill_value_str = "backward-fill"
            extra_stats    = {"method": "Backward Fill (next valid value)"}
            print(f"  [Impute-Bfill]  '{column}': filled {missing_count} backward")

        # ── fill_interpolate ──────────────────────────────────────
        elif strategy == "fill_interpolate":
            if pd.api.types.is_numeric_dtype(series):
                df[column]     = series.interpolate(method="linear", limit_direction="both")
                fill_value_str = "linear-interpolate"
                extra_stats    = {"method": "Linear Interpolation (time-series)"}
                print(f"  [Impute-Interp] '{column}': interpolated {missing_count} values")
            else:
                # Non-numeric: fall back to forward fill
                df[column]     = series.ffill()
                fill_value_str = "forward-fill (interpolate fallback)"
                extra_stats    = {"method": "Forward Fill (non-numeric interpolate fallback)"}
                print(f"  [Impute-Ffill]  '{column}': interpolate fallback → forward-filled {missing_count}")

        # ── fill_constant ────────────────────────────────────────
        elif strategy == "fill_constant":
            val = constant_value if constant_value is not None else "Unknown"
            df[column]     = series.fillna(val)
            fill_value_str = str(val)
            extra_stats    = {"method": "Constant Fill", "constant": val}
            print(f"  [Impute-Const]  '{column}': filled {missing_count} -> '{val}'")

        # ── Record audit log ─────────────────────────────────────
        if fill_value_str is not None:
            self.statistical_log.append({
                "column":      column,
                "strategy":    strategy,
                "fill_value":  fill_value_str,
                "rows_filled": missing_count,
                "missing_pct": round(missing_count / total_rows * 100, 1),
                "total_rows":  total_rows,
                "phase":       "Statistical Fallback",
                **extra_stats,
            })

        return df

    # ─────────────────────────────────────────────────────────────
    # KNN helper
    # ─────────────────────────────────────────────────────────────
    def _knn_impute(self, df: pd.DataFrame, column: str, missing_count: int):
        """Use sklearn KNNImputer on numeric columns only."""
        if not SKLEARN_AVAILABLE:
            # Fall back to median if sklearn not installed
            print(f"  [KNN] sklearn not available, falling back to median for '{column}'")
            median_val = float(df[column].dropna().median())
            df[column] = df[column].fillna(median_val)
            return df, True

        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        if column not in numeric_cols or len(numeric_cols) < 2:
            # Not enough context columns for KNN — fall back to median
            median_val = float(df[column].dropna().median())
            df[column] = df[column].fillna(median_val)
            return df, True

        imputer = KNNImputer(n_neighbors=min(5, len(df) - 1))
        df[numeric_cols] = imputer.fit_transform(df[numeric_cols])
        return df, True

    # ─────────────────────────────────────────────────────────────
    # Stats helpers
    # ─────────────────────────────────────────────────────────────
    @staticmethod
    def _numeric_stats(non_null: pd.Series) -> dict:
        if non_null.empty:
            return {
                "mean": None, "median": None, "std": None,
                "skewness": None, "min": None, "max": None
            }
        return {
            "mean":     round(float(non_null.mean()), 4),
            "median":   round(float(non_null.median()), 4),
            "std":      round(float(non_null.std()) if len(non_null) > 1 else 0.0, 4),
            "skewness": round(float(non_null.skew()) if len(non_null) > 2 else 0.0, 4),
            "min":      round(float(non_null.min()), 4),
            "max":      round(float(non_null.max()), 4),
        }

    @staticmethod
    def _categorical_stats(non_null: pd.Series) -> dict:
        top_vals = (
            non_null.value_counts(normalize=True)
            .head(5)
            .round(4)
            .to_dict()
        )
        return {
            "unique_vals":      int(non_null.nunique()),
            "top_distribution": {str(k): f"{v*100:.1f}%" for k, v in top_vals.items()},
        }

    # ─────────────────────────────────────────────────────────────
    # Condition parser for LLM rules
    # ─────────────────────────────────────────────────────────────
    @staticmethod
    def _parse_condition(df: pd.DataFrame, condition: str) -> pd.Series:
        """
        Parse simple LLM-generated conditions into boolean Series masks.
        Supports:
            column == 'value'
            column != 'value'
            column > number
            column < number
        """
        condition = condition.strip()

        # column == 'value' or column != 'value'
        m = re.match(r"(\w+)\s*(==|!=)\s*['\"](.+?)['\"]", condition)
        if m:
            col, op, val = m.group(1), m.group(2), m.group(3)
            if col in df.columns:
                mask = df[col].astype(str).str.strip().str.lower() == val.lower()
                return mask if op == "==" else ~mask

        # column > number or column < number
        m = re.match(r"(\w+)\s*(>|<|>=|<=)\s*([\d.]+)", condition)
        if m:
            col, op, val = m.group(1), m.group(2), float(m.group(3))
            if col in df.columns and pd.api.types.is_numeric_dtype(df[col]):
                ops = {">": pd.Series.gt, "<": pd.Series.lt,
                       ">=": pd.Series.ge, "<=": pd.Series.le}
                return ops[op](df[col], val)

        # Unparseable → no-op
        return pd.Series(False, index=df.index)
