"""
Advanced missing values imputation with:
- LLM-guided context-aware conditional rules
- Statistical fallbacks: mean, median, mode
- KNN-based imputation for numeric columns
- Forward/Backward fill for time-series ordered data
- Constant fill with domain defaults
Full audit tracking of every fill decision.
"""
import re
import pandas as pd
import numpy as np
from typing import List, Optional
from agents.planner_agent import ImputationRule

try:
    from sklearn.impute import KNNImputer
    SKLEARN_AVAILABLE = True
except ImportError:
    SKLEARN_AVAILABLE = False


# Sentinel strings that are treated the same as NaN
_NULL_STRINGS = {"", "nan", "none", "<na>", "unknown", "-", "n/a", "null", "?", "na"}


def _is_effectively_null(val) -> bool:
    if pd.isna(val):
        return True
    return str(val).strip().lower() in _NULL_STRINGS


class SmartImputer:
    """
    Multi-phase imputation engine:

    Phase 1 — LLM Contextual Rules:
        AI-generated conditional rules like "IF customer_type == 'B2B' THEN priority = 'High'"

    Phase 2 — Statistical Fallback (per-column strategy):
        fill_median, fill_mean, fill_mode, fill_knn, fill_constant,
        fill_forward, fill_backward, leave_empty

    All decisions are tracked in:
        self.applied_rules      — LLM rule results
        self.statistical_log    — statistical fill results
    """

    def __init__(self):
        self.applied_rules   = []   # LLM rule fills
        self.statistical_log = []   # statistical fallback fills

    # ─────────────────────────────────────────────────────────────
    # Phase 1: LLM Contextual Rules
    # ─────────────────────────────────────────────────────────────
    def apply_smart_rules(
        self, df: pd.DataFrame, rules: List[ImputationRule]
    ) -> pd.DataFrame:
        """Apply context-aware imputation rules generated by the LLM planner."""
        if not rules:
            return df

        print("  [SmartImputer] Applying LLM contextual rules...")
        sorted_rules = sorted(rules, key=lambda r: r.confidence, reverse=True)

        for rule in sorted_rules:
            col = rule.target_column
            if col not in df.columns:
                continue

            missing_mask = df[col].apply(_is_effectively_null)
            if missing_mask.sum() == 0:
                continue

            if rule.condition.lower() == "always":
                condition_mask = pd.Series(True, index=df.index)
            else:
                condition_mask = self._parse_condition(df, rule.condition)

            fill_mask    = missing_mask & condition_mask
            filled_count = int(fill_mask.sum())

            if filled_count > 0:
                df.loc[fill_mask, col] = rule.fill_value
                self.applied_rules.append({
                    "column":      col,
                    "condition":   rule.condition,
                    "fill_value":  rule.fill_value,
                    "rows_filled": filled_count,
                    "confidence":  rule.confidence,
                    "phase":       "LLM Rule",
                })
                print(
                    f"    -> Filled {filled_count} in '{col}' "
                    f"with '{rule.fill_value}' [{rule.condition}]"
                )

        return df

    # ─────────────────────────────────────────────────────────────
    # Phase 2: Statistical Fallback Imputation
    # ─────────────────────────────────────────────────────────────
    def apply_statistical(
        self, df: pd.DataFrame, column: str, strategy: str,
        constant_value: Optional[str] = None,
    ) -> pd.DataFrame:
        """
        Apply statistical imputation and record detailed audit stats.

        Supported strategies:
            fill_median   — robust for skewed numeric data
            fill_mean     — best for normally distributed numeric data
            fill_mode     — best for categorical / low-cardinality columns
            fill_knn      — KNN imputation for numeric (uses sklearn)
            fill_forward  — propagate last valid value forward
            fill_backward — propagate next valid value backward
            fill_constant — fill with a specific provided constant
            leave_empty   — do nothing (explicit skip)
        """
        if strategy == "leave_empty" or column not in df.columns:
            return df

        series = df[column]

        # Unified missing mask: NaN + sentinel strings
        is_missing = series.apply(_is_effectively_null)
        # Standardize sentinel strings to actual NaN first
        df.loc[is_missing, column] = np.nan
        series = df[column]

        missing_count = int(series.isna().sum())
        if missing_count == 0:
            return df

        total_rows = len(series)
        non_null   = series.dropna()
        fill_value_str = None
        extra_stats    = {}

        # ── fill_median ──────────────────────────────────────────
        if strategy == "fill_median" and pd.api.types.is_numeric_dtype(series):
            median_val     = float(non_null.median())
            fill_value_str = f"{median_val:.4g}"
            df[column]     = series.fillna(median_val)
            extra_stats    = self._numeric_stats(non_null)
            print(f"  [Impute-Median] '{column}': filled {missing_count} → {median_val:.4g}")

        # ── fill_mean ────────────────────────────────────────────
        elif strategy == "fill_mean" and pd.api.types.is_numeric_dtype(series):
            mean_val       = float(non_null.mean())
            fill_value_str = f"{mean_val:.4g}"
            df[column]     = series.fillna(mean_val)
            extra_stats    = self._numeric_stats(non_null)
            print(f"  [Impute-Mean]   '{column}': filled {missing_count} → {mean_val:.4g}")

        # ── fill_mode ────────────────────────────────────────────
        elif strategy == "fill_mode":
            mode_series = non_null.mode()
            if not mode_series.empty:
                mode_val       = mode_series.iloc[0]
                fill_value_str = str(mode_val)
                df[column]     = series.fillna(mode_val)
                extra_stats    = self._categorical_stats(non_null)
                print(f"  [Impute-Mode]   '{column}': filled {missing_count} → '{mode_val}'")

        # ── fill_knn ─────────────────────────────────────────────
        elif strategy == "fill_knn" and pd.api.types.is_numeric_dtype(series):
            df, knn_filled = self._knn_impute(df, column, missing_count)
            if knn_filled:
                fill_value_str = "KNN"
                extra_stats    = {"method": "KNN (k=5)", "imputed_cells": missing_count}
                print(f"  [Impute-KNN]    '{column}': filled {missing_count} using KNN")

        # ── fill_forward ─────────────────────────────────────────
        elif strategy == "fill_forward":
            df[column]     = series.ffill()
            fill_value_str = "forward-fill"
            extra_stats    = {"method": "Forward Fill (last valid value)"}
            print(f"  [Impute-Ffill]  '{column}': filled {missing_count} forward")

        # ── fill_backward ────────────────────────────────────────
        elif strategy == "fill_backward":
            df[column]     = series.bfill()
            fill_value_str = "backward-fill"
            extra_stats    = {"method": "Backward Fill (next valid value)"}
            print(f"  [Impute-Bfill]  '{column}': filled {missing_count} backward")

        # ── fill_constant ────────────────────────────────────────
        elif strategy == "fill_constant":
            val = constant_value if constant_value is not None else "Unknown"
            df[column]     = series.fillna(val)
            fill_value_str = str(val)
            extra_stats    = {"method": "Constant Fill", "constant": val}
            print(f"  [Impute-Const]  '{column}': filled {missing_count} → '{val}'")

        # ── Record audit log ─────────────────────────────────────
        if fill_value_str is not None:
            self.statistical_log.append({
                "column":      column,
                "strategy":    strategy,
                "fill_value":  fill_value_str,
                "rows_filled": missing_count,
                "missing_pct": round(missing_count / total_rows * 100, 1),
                "total_rows":  total_rows,
                "phase":       "Statistical Fallback",
                **extra_stats,
            })

        return df

    # ─────────────────────────────────────────────────────────────
    # KNN helper
    # ─────────────────────────────────────────────────────────────
    def _knn_impute(self, df: pd.DataFrame, column: str, missing_count: int):
        """Use sklearn KNNImputer on numeric columns only."""
        if not SKLEARN_AVAILABLE:
            # Fall back to median if sklearn not installed
            print(f"  [KNN] sklearn not available, falling back to median for '{column}'")
            median_val = float(df[column].dropna().median())
            df[column] = df[column].fillna(median_val)
            return df, True

        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        if column not in numeric_cols or len(numeric_cols) < 2:
            # Not enough context columns for KNN — fall back to median
            median_val = float(df[column].dropna().median())
            df[column] = df[column].fillna(median_val)
            return df, True

        imputer = KNNImputer(n_neighbors=min(5, len(df) - 1))
        df[numeric_cols] = imputer.fit_transform(df[numeric_cols])
        return df, True

    # ─────────────────────────────────────────────────────────────
    # Stats helpers
    # ─────────────────────────────────────────────────────────────
    @staticmethod
    def _numeric_stats(non_null: pd.Series) -> dict:
        return {
            "mean":     round(float(non_null.mean()), 4),
            "median":   round(float(non_null.median()), 4),
            "std":      round(float(non_null.std()) if len(non_null) > 1 else 0.0, 4),
            "skewness": round(float(non_null.skew()) if len(non_null) > 2 else 0.0, 4),
            "min":      round(float(non_null.min()), 4),
            "max":      round(float(non_null.max()), 4),
        }

    @staticmethod
    def _categorical_stats(non_null: pd.Series) -> dict:
        top_vals = (
            non_null.value_counts(normalize=True)
            .head(5)
            .round(4)
            .to_dict()
        )
        return {
            "unique_vals":      int(non_null.nunique()),
            "top_distribution": {str(k): f"{v*100:.1f}%" for k, v in top_vals.items()},
        }

    # ─────────────────────────────────────────────────────────────
    # Condition parser for LLM rules
    # ─────────────────────────────────────────────────────────────
    @staticmethod
    def _parse_condition(df: pd.DataFrame, condition: str) -> pd.Series:
        """
        Parse simple LLM-generated conditions into boolean Series masks.
        Supports:
            column == 'value'
            column != 'value'
            column > number
            column < number
        """
        condition = condition.strip()

        # column == 'value' or column != 'value'
        m = re.match(r"(\w+)\s*(==|!=)\s*['\"](.+?)['\"]", condition)
        if m:
            col, op, val = m.group(1), m.group(2), m.group(3)
            if col in df.columns:
                mask = df[col].astype(str).str.strip().str.lower() == val.lower()
                return mask if op == "==" else ~mask

        # column > number or column < number
        m = re.match(r"(\w+)\s*(>|<|>=|<=)\s*([\d.]+)", condition)
        if m:
            col, op, val = m.group(1), m.group(2), float(m.group(3))
            if col in df.columns and pd.api.types.is_numeric_dtype(df[col]):
                ops = {">": pd.Series.gt, "<": pd.Series.lt,
                       ">=": pd.Series.ge, "<=": pd.Series.le}
                return ops[op](df[col], val)

        # Unparseable → no-op
        return pd.Series(False, index=df.index)
